//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiWebService.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anuncios
    {
        public int id { get; set; }
        public string comunidadAutonoma { get; set; }
        public string provincia { get; set; }
        public string localidad { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> idMoto { get; set; }
        public Nullable<int> idUsuario { get; set; }
    
        public virtual Motos Motos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
