//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiWebService.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reparaciones
    {
        public int id { get; set; }
        public Nullable<int> idReparacion { get; set; }
        public string diagnostico { get; set; }
        public string explicacion { get; set; }
        public string estado { get; set; }
        public Nullable<double> prefio { get; set; }
        public Nullable<int> idMoto { get; set; }
        public Nullable<int> idTaller { get; set; }
        public Nullable<int> idValoracion { get; set; }
    
        public virtual Motos Motos { get; set; }
        public virtual Talleres Talleres { get; set; }
        public virtual Valoraciones Valoraciones { get; set; }
    }
}
