//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiWebService.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Valoraciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Valoraciones()
        {
            this.Reparaciones = new HashSet<Reparaciones>();
        }
    
        public int id { get; set; }
        public Nullable<int> idTaller { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public string comentario { get; set; }
        public Nullable<byte> nota { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reparaciones> Reparaciones { get; set; }
        public virtual Talleres Talleres { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
